### ISSUE TITLE
Remove Sense Enterprise references from QIX documentation 

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/core-website#268]
There are multiple mentions of Qlik Sense as well as methods only applicable on a Sense installation.
Some examples:

https://www.qlikcore.com/docs/services/qix-engine/apis/qix/global/#copyapp
https://www.qlikcore.com/docs/services/qix-engine/apis/qix/doc/#publish
https://www.qlikcore.com/docs/services/qix-engine/apis/qix/doc/#scramble

**Comment by peol** [comment]
I think this needs to be solved using the internal issue tracker?
