### ISSUE TITLE
Misleading Engine documentation

### ISSUE THREAD

**Issue by stefanwalther** [qlik-oss/core-website#276]
Hi, I think there's something wrong with this section:

![image](https://user-images.githubusercontent.com/669728/39825184-7ed24584-53b1-11e8-866e-b87ab7b20870.png)

The statement of `Use the GetBaseBNF method instead` is not related to the header `GetAuthenticatedUser`, right?

Seen here: https://qlikcore.com/docs/services/qix-engine/apis/qix/global/

**Comment by peol** [comment]
You're right, for some reason the formatting is off in the markdown file causing the mkdocs tool we're using to generate HTML to drop the header, probably something that needs fixing in our internal markdown generator tool:

https://github.com/qlik-oss/core-website/blob/master/docs/docs/services/qix-engine/apis/qix/global.md#getbnf
