### ISSUE TITLE
Document websocket url structure

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/core-website#277]
For the QIX api and related to the websocket url we are missing documentation on certain parameters such as `identity` and `ttl` and its corresponding command line property.

**Comment by peol** [comment]
`identity` is pretty Sense-specific and doesn't mean much in Core. I'll check what the status for `ttl` is, AFAIK it's still a private API.

**Comment by peol** [comment]
We can certainly do that, but the current design approach has been to leave that up to the Qlik Core user (proxy in front of engine).

We have the headers documented which does exactly what you're asking for (`x-qlik-session`: https://qlikcore.com/docs/services/qix-engine/apis/qix/introduction/#headers). Earlier on that same page we also document `/app/<unique identifier>`. I might be missing what you're asking for?

**Comment by mindspank** [comment]
So an example could be the same user opening the same application in two separate browser tabs and does not want to share selection state between the browser tabs.

I guess we could use the header for this or a random value in the `app` identifier.

I’m not keen on using the header as you probably want to mimic that session id with an external system.

Kind Regards,
Alexander Karlsson
________________________________

**Comment by janmiderback** [comment]
@mindspank Please check current documentation at https://qlikcore.com/docs/services/qix-engine/apis/qix/introduction/#websockets and subsections to see if it fulfills requirements in this issue.

**Comment by mindspank** [comment]
@janmiderback looks *very* good

**Comment by janmiderback** [comment]
@mindspank Thanks. Close issue?
