### ISSUE TITLE
Add and update Use Cases documentation

### ISSUE THREAD

**Issue by janmiderback** [qlik-oss/core-website#316]
Update the Qlik Core documentation to cover our two Use Cases:
- Assisted Prescription, and
- African Urbanization

#### Suggested Changes

- [ ] Remove everything under Documentation->Tutorials->Scalability
- [ ] Under Documentation->Home: Change the section name "Live Demo" to "Use Cases". Remove the text specifically mentioning the "AP" use case and instead point to the new single page under Documentation->Use Cases. Explain what can be found there.
- [ ] Introduce a new section at top-level: Documentation-> Use Cases. This new section could come last. Try to keep the size of the contents to one page that covers both demos. Add some introductory text on what purpose the demos serve generally and then link to two subsections on the page covering each demo.
- [ ] Assisted Prescription subsection
  - [ ] Business Problem Solved
  - [ ] Conceptual Architecture Diagram
  - [ ] Technologies Showcased (e.g. Swarm)
- [ ] African Urbanization subsection
  - [ ] Business Problem Solved
  - [ ] Conceptual Architecture Diagram
  - [ ] Technologies Showcased (e.g.Kubernetes)

**Comment by janmiderback** [comment]
Good points. If we have settled for "Use Cases" then we should stick to it. Personally, I feel that the term "use case" is a bit misused here, why I favor "Demo" or "Live Demo". Updating suggested order.

**Comment by janmiderback** [comment]
After some thought, I think we should stick to "Use Cases". Updated.

**Comment by sublibra** [comment]
Great summary @janmiderback. I like the suggested above! Keeping the overview page short is a good idea since we most probably will add more use cases later.

**Comment by hrigner** [comment]
This looks good to me! Thumbs up for the term "use cases" and having business problem first in the use case section.

**Comment by janmiderback** [comment]
Spawning out other tasks from this. Closing.
