### ISSUE TITLE
Missing command line parameters for Analytical Connector API

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/core-website#317]
Currently we are not documenting the command line switches needed to register a analytical connector with the qlik associative engine.

We are mentioning a Qlik Sense Desktop scenario here: https://help.qlik.com/en-US/sense/April2018/Subsystems/Hub/Content/Introduction/configure-analytic-connection-desktop.htm but are currently not documenting those switches for Core

**Comment by wennmo** [comment]
Solved in #352.

How to configure an Analytical Connector in Qlik Core is now documented:
https://qlikcore.com/services/qix-engine/apis/server-side-extension/introduction/#how-to-configure-an-analytical-connector-in-qlik-core

Also added an overview of available Qlik Associative Engine command line parameters:
https://qlikcore.com/services/qix-engine/introduction/#command-line-parameters
