### ISSUE TITLE
Create a weekly job checking for broken links

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/core-website#344]
Investigate what automatic services exists and evaluate against using our per commit script to do the same.

**Comment by carlioth** [comment]
I've created the code for link checking, and fine tuned it. It will check around 1530 link per run. 
Left of this task is to: 
* Create CRON job on tooling instance. 
* Post to Slack when finding broken links. 
* Check in to Git repo.

**Comment by sublibra** [comment]
We have a broken link checker on every commit.
