### ISSUE TITLE
Sitemap.xml still not generated in production

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/core-website#398]
Generated on our test environment but not in production

**Comment by peol** [comment]
It is, manually forcing a cloudfront invalidation works, so it looks like our s3/cloudfront invalidation step in circle ci is not working.

The newly deployed content will however be accessible ~24h after being deployed without the invalidation mechanism so it's not a blocket in my book.

**Comment by sublibra** [comment]
The issue was not immediately fixed due to slow cache invalidation.
