### ISSUE TITLE
On this page menu get stuck

### ISSUE THREAD

**Issue by JohanBjerning** [qlik-oss/core-website#490]
![image (3)](https://user-images.githubusercontent.com/18257985/54675308-9ac10380-4afe-11e9-89fa-d5784f74f922.png)

**Comment by peol** [comment]
And while we're at it, at certain widths the TOC/menus only shows "..." :)

![Screenshot 2019-03-20 at 13 15 19](https://user-images.githubusercontent.com/83221/54683584-46278380-4b12-11e9-8147-60c6f782a4c6.png)
