### ISSUE TITLE
Core.qlik.com documentation link leads to 404 error

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/core-website#563]
https://core.qlik.com/index.md returns with a 404. I presume this page should not be missing.

**Comment by sublibra** [comment]
md-files should not be referenced directly. They are 
https://github.com/qlik-oss/core-website/blob/master/docs/downloads.md

becomes
https://core.qlik.com/downloads/

when the website is built.

Did you find this in a link somewhere?
